version: '3'
services:
  vpnz:
    image: vpnzs:latest
    restart: always
    container_name: vpnz
    ports:
      - "2578:8888"   
      - "2560:2560"
      - "2564:2564"
    shm_size: '200gb'
    command: bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    volumes:
      - /gitdrive/vpnz:/app/project/data


---

version: '3'
services:
  vpn:
    image: vpns:latest
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    restart: always
    container_name: vpn
    ports:
      - "2525:8888"     
    shm_size: '200gb'
    command: bash -c "jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root"
    volumes:
      - /drivey/vpn:/app/project/test_data