version: '3.8'

services:
  machine1:
    image: alpine:latest
    container_name: machine1
    cap_add:
      - NET_ADMIN
    networks:
      - wg_network
    command: >
      sh -c "apk add --no-cache net-tools git &&
             tail -f /dev/null"

  machine2:
    image: alpine:latest
    container_name: machine2
    cap_add:
      - NET_ADMIN
    networks:
      - wg_network
    command: >
      sh -c "apk add --no-cache net-tools git &&
             tail -f /dev/null"

  machine3:
    image: alpine:latest
    container_name: machine3
    cap_add:
      - NET_ADMIN
    networks:
      - wg_network
    command: >
      sh -c "apk add --no-cache net-tools git &&
             tail -f /dev/null"

networks:
  wg_network:
    driver: bridge