
services:
  alma1:
    build: .
    container_name: alma1
    hostname: alma1
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    ports:
      - "8080:8080"
    networks:
      almanet:
        ipv4_address: 172.20.0.10
    cap_add:
      - NET_ADMIN
    command: python3 /shared/Servidor/server.py 172.20.0.10 # <-- Ejecuta el server

  alma2:
    build: .
    container_name: alma2
    hostname: alma2
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.11
    cap_add:
      - NET_ADMIN
    command: python3 /shared/Cliente/client-as-deamon.py 172.20.0.10 172.20.0.11 # <-- Cliente (alma2)

  alma3:
    build: .
    container_name: alma3
    hostname: alma3
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.12
    cap_add:
      - NET_ADMIN
    command: python3 /shared/Cliente/client-as-deamon.py 172.20.0.10 172.20.0.12 # <-- Cliente (alma3)

networks:
  almanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
