version: '3.8'

services:
  alma1:
    build: .
    container_name: alma1
    hostname: alma1
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    networks:
      almanet:
        ipv4_address: 172.20.0.10
    cap_add:
      - NET_ADMIN

  alma2:
    build: .
    container_name: alma2
    hostname: alma2
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.11
    cap_add:
      - NET_ADMIN

  alma3:
    build: .
    container_name: alma3
    hostname: alma3
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.12
    cap_add:
      - NET_ADMIN

networks:
  almanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24