
services:
  alma1:
    build: .
    container_name: alma1
    hostname: alma1
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.10
    cap_add: [NET_ADMIN]
    # Server: escucha en 8000
    command: python3 /shared/Servidor/server.py 172.20.0.10
    ports:
      - "8080:8080"
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  alma2:
    build: .
    container_name: alma2
    hostname: alma2
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.11
    cap_add: [NET_ADMIN]
    depends_on: [alma1]
    # Cliente: daemon con su IP de transporte
    command: python3 /shared/Cliente/client-as-deamon.py 172.20.0.10 172.20.0.11
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  alma3:
    build: .
    container_name: alma3
    hostname: alma3
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.12
    cap_add: [NET_ADMIN]
    depends_on: [alma1]
    command: python3 /shared/Cliente/client-as-deamon.py 172.20.0.10 172.20.0.12
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  # Tercer peer (solo se levanta con --profile three)
  alma4:
    build: .
    container_name: alma4
    hostname: alma4
    tty: true
    stdin_open: true
    volumes:
      - ./shared:/shared
    networks:
      almanet:
        ipv4_address: 172.20.0.13
    cap_add: [NET_ADMIN]
    depends_on: [alma1]
    command: python3 /shared/Cliente/client-as-deamon.py 172.20.0.10 172.20.0.13
    profiles: ["three"]
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  almanet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
