# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuración común para todas las máquinas
  config.vm.box = "ubuntu/focal64"  # Usamos Ubuntu 20.04 LTS como base

  # Definición de las máquinas virtuales
  config.vm.define "vm1" do |vm1|
    vm1.vm.hostname = "vm1"
    vm1.vm.network "private_network", ip: "192.168.56.101"
    vm1.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y wireguard net-tools git
    SHELL
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.hostname = "vm2"
    vm2.vm.network "private_network", ip: "192.168.56.102"
    vm2.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y wireguard net-tools git
    SHELL
  end

  config.vm.define "vm3" do |vm3|
    vm3.vm.hostname = "vm3"
    vm3.vm.network "private_network", ip: "192.168.56.103"
    vm3.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y wireguard net-tools git
    SHELL
  end
end